site_name: Your Working group Documentation
theme:
  name: material
  logo: assets/logos/enigma_300DPI_small.png
  favicon: assets/logos/enigma_300DPI_small.png
  palette:
    primary: teal
  

features:
  - navigation.indexes

nav:
  - Welcome: index.md

  - About XYZ WG:    
    - Core team: working_group/team.md
    - Sites: working_group/existing_sites.md
    - Information for new sites: working_group/new_sites.md
    
  - Ongoing Projects: 
    - Overview: ongoing_projects/overview.md
    - Example Project: ongoing_projects/example_active_project.md

  - Completed Projects: 
    - Overview: completed_projects/overview.md
    - Example Completed Project: completed_projects/example_completed_project.md


  - Resources: 
    - Overview: resources/overview.md


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg